python scripts/job_runner.py 15 "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_5_n02_10_05_00_bb_580444/models/gmm_10.npy --eval-out /tmp/sd_model_eval_580444.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_5_n01_15_10_00_bb_0f8246/models/gmm_26.npy --eval-out /tmp/sd_model_eval_0f8246.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_5_n00_10_10_00_hpo_79a820/models/gmm_10.npy --eval-out /tmp/sd_model_eval_79a820.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_5_n00_10_05_00_bb_862ce3/models/gmm_13.npy --eval-out /tmp/sd_model_eval_862ce3.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_3_n02_15_05_25_hpo_fa8515/models/gmm_46.npy --eval-out /tmp/sd_model_eval_fa8515.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_3_n01_10_10_25_hpo_68e87c/models/gmm_31.npy --eval-out /tmp/sd_model_eval_68e87c.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_7_n02_15_05_00_bb_f417a7/models/gmm_6.npy --eval-out /tmp/sd_model_eval_f417a7.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_7_n01_15_05_00_bb_82e007/models/gmm_13.npy --eval-out /tmp/sd_model_eval_82e007.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_7_n00_15_05_00_hpo_55702c/models/gmm_6.npy --eval-out /tmp/sd_model_eval_55702c.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_7_n00_15_05_00_bb_0d04c8/models/gmm_2.npy --eval-out /tmp/sd_model_eval_0d04c8.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_7_n00_10_05_25_bb_188693/models/gmm_14.npy --eval-out /tmp/sd_model_eval_188693.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_5_n02_15_05_00_hpo_375dfd/models/gmm_13.npy --eval-out /tmp/sd_model_eval_375dfd.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_5_n02_10_10_00_bb_ffbac6/models/gmm_13.npy --eval-out /tmp/sd_model_eval_ffbac6.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_5_n01_10_05_00_bb_823c53/models/gmm_10.npy --eval-out /tmp/sd_model_eval_823c53.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_5_n00_15_10_00_bb_30ea8f/models/gmm_13.npy --eval-out /tmp/sd_model_eval_30ea8f.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_5_n00_10_05_00_hpo_0523c5/models/gmm_17.npy --eval-out /tmp/sd_model_eval_0523c5.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_3_n01_15_05_00_hpo_b8c798/models/gmm_2.npy --eval-out /tmp/sd_model_eval_b8c798.csv" \
                                "python scripts/main.py sliding_door_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=/home/aroefer/bopt_gmm_exp_sd_ss/smac_50_3_n01_10_05_25_hpo_a67a44/models/gmm_46.npy --eval-out /tmp/sd_model_eval_a67a44.csv"
python scripts/csv_fusion.py results/sd_model_eval.csv /tmp/sd_model_eval_*.csv