python scripts/job_runner.py 15 "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/gmm/drawer_7p.npy --eval-out /tmp/baselines_drawer_7p_n00.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/gmm/drawer_7p.npy --eval-out /tmp/baselines_drawer_7p_n01.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/gmm/drawer_7p.npy --eval-out /tmp/baselines_drawer_7p_n02.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/gmm/drawer_7p.npy --eval-out /tmp/baselines_drawer_7p_n03.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/gmm/drawer_7p.npy --eval-out /tmp/baselines_drawer_7p_n05.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/gmm/drawer_5p.npy --eval-out /tmp/baselines_drawer_5p_n00.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/gmm/drawer_5p.npy --eval-out /tmp/baselines_drawer_5p_n01.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/gmm/drawer_5p.npy --eval-out /tmp/baselines_drawer_5p_n02.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/gmm/drawer_5p.npy --eval-out /tmp/baselines_drawer_5p_n03.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/gmm/drawer_5p.npy --eval-out /tmp/baselines_drawer_5p_n05.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/gmm/drawer_3p.npy --eval-out /tmp/baselines_drawer_3p_n00.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/gmm/drawer_3p.npy --eval-out /tmp/baselines_drawer_3p_n01.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/gmm/drawer_3p.npy --eval-out /tmp/baselines_drawer_3p_n02.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/gmm/drawer_3p.npy --eval-out /tmp/baselines_drawer_3p_n03.csv" \
                                "python scripts/main.py drawer_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/gmm/drawer_3p.npy --eval-out /tmp/baselines_drawer_3p_n05.csv"
python scripts/csv_fusion.py data/baselines_drawer.csv /tmp/baselines_drawer_*.csv