python scripts/job_runner.py 5  "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_geom.npz --bc-inputs position --eval-out /tmp/baselines_door_bc_lstm_geom_n00.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_geom.npz --bc-inputs position --eval-out /tmp/baselines_door_bc_lstm_geom_n01.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_geom.npz --bc-inputs position --eval-out /tmp/baselines_door_bc_lstm_geom_n02.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_geom.npz --bc-inputs position --eval-out /tmp/baselines_door_bc_lstm_geom_n03.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_js.npz --bc-inputs position doorpos --eval-out /tmp/baselines_door_bc_lstm_js_n00.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_js.npz --bc-inputs position doorpos --eval-out /tmp/baselines_door_bc_lstm_js_n01.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_js.npz --bc-inputs position doorpos --eval-out /tmp/baselines_door_bc_lstm_js_n02.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_js.npz --bc-inputs position doorpos --eval-out /tmp/baselines_door_bc_lstm_js_n03.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_f.npz --bc-inputs position force --eval-out /tmp/baselines_door_bc_lstm_f_n00.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_f.npz --bc-inputs position force --eval-out /tmp/baselines_door_bc_lstm_f_n01.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_f.npz --bc-inputs position force --eval-out /tmp/baselines_door_bc_lstm_f_n02.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_f.npz --bc-inputs position force --eval-out /tmp/baselines_door_bc_lstm_f_n03.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_t.npz --bc-inputs position torque --eval-out /tmp/baselines_door_bc_lstm_t_n00.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_t.npz --bc-inputs position torque --eval-out /tmp/baselines_door_bc_lstm_t_n01.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_t.npz --bc-inputs position torque --eval-out /tmp/baselines_door_bc_lstm_t_n02.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_t.npz --bc-inputs position torque --eval-out /tmp/baselines_door_bc_lstm_t_n03.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_ft.npz --bc-inputs position force torque --eval-out /tmp/baselines_door_bc_lstm_ft_n00.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_ft.npz --bc-inputs position force torque --eval-out /tmp/baselines_door_bc_lstm_ft_n01.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_ft.npz --bc-inputs position force torque --eval-out /tmp/baselines_door_bc_lstm_ft_n02.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_ft.npz --bc-inputs position force torque --eval-out /tmp/baselines_door_bc_lstm_ft_n03.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_geom_100.npz --bc-inputs position --eval-out /tmp/baselines_door_bc_lstm_geom_100_n00.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_geom_100.npz --bc-inputs position --eval-out /tmp/baselines_door_bc_lstm_geom_100_n01.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_geom_100.npz --bc-inputs position --eval-out /tmp/baselines_door_bc_lstm_geom_100_n02.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_geom_100.npz --bc-inputs position --eval-out /tmp/baselines_door_bc_lstm_geom_100_n03.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_js_100.npz --bc-inputs position doorpos --eval-out /tmp/baselines_door_bc_lstm_js_100_n00.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_js_100.npz --bc-inputs position doorpos --eval-out /tmp/baselines_door_bc_lstm_js_100_n01.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_js_100.npz --bc-inputs position doorpos --eval-out /tmp/baselines_door_bc_lstm_js_100_n02.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_js_100.npz --bc-inputs position doorpos --eval-out /tmp/baselines_door_bc_lstm_js_100_n03.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_f_100.npz --bc-inputs position force --eval-out /tmp/baselines_door_bc_lstm_f_100_n00.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_f_100.npz --bc-inputs position force --eval-out /tmp/baselines_door_bc_lstm_f_100_n01.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_f_100.npz --bc-inputs position force --eval-out /tmp/baselines_door_bc_lstm_f_100_n02.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_f_100.npz --bc-inputs position force --eval-out /tmp/baselines_door_bc_lstm_f_100_n03.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_t_100.npz --bc-inputs position torque --eval-out /tmp/baselines_door_bc_lstm_t_100_n00.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_t_100.npz --bc-inputs position torque --eval-out /tmp/baselines_door_bc_lstm_t_100_n01.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_t_100.npz --bc-inputs position torque --eval-out /tmp/baselines_door_bc_lstm_t_100_n02.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_t_100.npz --bc-inputs position torque --eval-out /tmp/baselines_door_bc_lstm_t_100_n03.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_ft_100.npz --bc-inputs position force torque --eval-out /tmp/baselines_door_bc_lstm_ft_100_n00.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_ft_100.npz --bc-inputs position force torque --eval-out /tmp/baselines_door_bc_lstm_ft_100_n01.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_ft_100.npz --bc-inputs position force torque --eval-out /tmp/baselines_door_bc_lstm_ft_100_n02.csv" \
                                "python scripts/main.py door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 env.robot.controller=virtual bopt_agent.num_episode_steps=200 bopt_agent.gmm.model=models/bc/door_lstm_ft_100.npz --bc-inputs position force torque --eval-out /tmp/baselines_door_bc_lstm_ft_100_n03.csv"
python scripts/csv_fusion.py data/baselines_door_bc.csv /tmp/baselines_door_bc_*.csv
