python scripts/job_runner.py 4  "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/gmm/peg_7p.npy --eval-out /tmp/baselines_peg_7p_n00.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/gmm/peg_7p.npy --eval-out /tmp/baselines_peg_7p_n01.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/gmm/peg_7p.npy --eval-out /tmp/baselines_peg_7p_n02.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/gmm/peg_7p.npy --eval-out /tmp/baselines_peg_7p_n03.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/gmm/peg_7p.npy --eval-out /tmp/baselines_peg_7p_n05.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/gmm/peg_5p.npy --eval-out /tmp/baselines_peg_5p_n00.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/gmm/peg_5p.npy --eval-out /tmp/baselines_peg_5p_n01.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/gmm/peg_5p.npy --eval-out /tmp/baselines_peg_5p_n02.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/gmm/peg_5p.npy --eval-out /tmp/baselines_peg_5p_n03.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/gmm/peg_5p.npy --eval-out /tmp/baselines_peg_5p_n05.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/gmm/peg_3p.npy --eval-out /tmp/baselines_peg_3p_n00.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/gmm/peg_3p.npy --eval-out /tmp/baselines_peg_3p_n01.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/gmm/peg_3p.npy --eval-out /tmp/baselines_peg_3p_n02.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/gmm/peg_3p.npy --eval-out /tmp/baselines_peg_3p_n03.csv" \
                                "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/gmm/peg_3p.npy --eval-out /tmp/baselines_peg_3p_n05.csv"
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/gmm/peg_7p_f.npy --eval-out /tmp/baselines_peg_7p_f_n00.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/gmm/peg_7p_f.npy --eval-out /tmp/baselines_peg_7p_f_n01.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/gmm/peg_7p_f.npy --eval-out /tmp/baselines_peg_7p_f_n02.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/gmm/peg_7p_f.npy --eval-out /tmp/baselines_peg_7p_f_n03.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/gmm/peg_7p_f.npy --eval-out /tmp/baselines_peg_7p_f_n05.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/gmm/peg_5p_f.npy --eval-out /tmp/baselines_peg_5p_f_n00.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/gmm/peg_5p_f.npy --eval-out /tmp/baselines_peg_5p_f_n01.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/gmm/peg_5p_f.npy --eval-out /tmp/baselines_peg_5p_f_n02.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/gmm/peg_5p_f.npy --eval-out /tmp/baselines_peg_5p_f_n03.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/gmm/peg_5p_f.npy --eval-out /tmp/baselines_peg_5p_f_n05.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/gmm/peg_3p_f.npy --eval-out /tmp/baselines_peg_3p_f_n00.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/gmm/peg_3p_f.npy --eval-out /tmp/baselines_peg_3p_f_n01.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/gmm/peg_3p_f.npy --eval-out /tmp/baselines_peg_3p_f_n02.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/gmm/peg_3p_f.npy --eval-out /tmp/baselines_peg_3p_f_n03.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/gmm/peg_3p_f.npy --eval-out /tmp/baselines_peg_3p_f_n05.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/gmm/peg_7p_f.npy --eval-out /tmp/baselines_peg_7p_f_n00.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/gmm/peg_7p_t.npy --eval-out /tmp/baselines_peg_7p_t_n01.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/gmm/peg_7p_t.npy --eval-out /tmp/baselines_peg_7p_t_n02.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/gmm/peg_7p_t.npy --eval-out /tmp/baselines_peg_7p_t_n03.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/gmm/peg_7p_t.npy --eval-out /tmp/baselines_peg_7p_t_n05.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/gmm/peg_5p_t.npy --eval-out /tmp/baselines_peg_5p_t_n00.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/gmm/peg_5p_t.npy --eval-out /tmp/baselines_peg_5p_t_n01.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/gmm/peg_5p_t.npy --eval-out /tmp/baselines_peg_5p_t_n02.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/gmm/peg_5p_t.npy --eval-out /tmp/baselines_peg_5p_t_n03.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/gmm/peg_5p_t.npy --eval-out /tmp/baselines_peg_5p_t_n05.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/gmm/peg_3p_t.npy --eval-out /tmp/baselines_peg_3p_t_n00.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/gmm/peg_3p_t.npy --eval-out /tmp/baselines_peg_3p_t_n01.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/gmm/peg_3p_t.npy --eval-out /tmp/baselines_peg_3p_t_n02.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/gmm/peg_3p_t.npy --eval-out /tmp/baselines_peg_3p_t_n03.csv" \
                                # "python scripts/main.py peg_dbopt --mode eval-gmm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/gmm/peg_3p_t.npy --eval-out /tmp/baselines_peg_3p_t_n05.csv"
python scripts/csv_fusion.py data/baselines_peg.csv /tmp/baselines_peg_*.csv