python scripts/job_runner.py 15 "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/bc/lstm_geom.npz --bc-inputs position --eval-out /tmp/baselines_sd_bc_lstm_geom_n00.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/bc/lstm_geom.npz --bc-inputs position --eval-out /tmp/baselines_sd_bc_lstm_geom_n01.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/bc/lstm_geom.npz --bc-inputs position --eval-out /tmp/baselines_sd_bc_lstm_geom_n02.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/bc/lstm_geom.npz --bc-inputs position --eval-out /tmp/baselines_sd_bc_lstm_geom_n03.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/bc/lstm_geom.npz --bc-inputs position --eval-out /tmp/baselines_sd_bc_lstm_geom_n05.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/bc/lstm_f.npz --bc-inputs position force --eval-out /tmp/baselines_sd_bc_lstm_f_n00.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/bc/lstm_f.npz --bc-inputs position force --eval-out /tmp/baselines_sd_bc_lstm_f_n01.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/bc/lstm_f.npz --bc-inputs position force --eval-out /tmp/baselines_sd_bc_lstm_f_n02.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/bc/lstm_f.npz --bc-inputs position force --eval-out /tmp/baselines_sd_bc_lstm_f_n03.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/bc/lstm_f.npz --bc-inputs position force --eval-out /tmp/baselines_sd_bc_lstm_f_n05.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/bc/lstm_t.npz --bc-inputs position torque --eval-out /tmp/baselines_sd_bc_lstm_t_n00.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/bc/lstm_t.npz --bc-inputs position torque --eval-out /tmp/baselines_sd_bc_lstm_t_n01.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/bc/lstm_t.npz --bc-inputs position torque --eval-out /tmp/baselines_sd_bc_lstm_t_n02.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/bc/lstm_t.npz --bc-inputs position torque --eval-out /tmp/baselines_sd_bc_lstm_t_n03.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/bc/lstm_t.npz --bc-inputs position torque --eval-out /tmp/baselines_sd_bc_lstm_t_n05.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.00 bopt_agent.gmm.model=models/bc/lstm_ft.npz --bc-inputs position force torque --eval-out /tmp/baselines_sd_bc_lstm_ft_n00.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.01 bopt_agent.gmm.model=models/bc/lstm_ft.npz --bc-inputs position force torque --eval-out /tmp/baselines_sd_bc_lstm_ft_n01.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.02 bopt_agent.gmm.model=models/bc/lstm_ft.npz --bc-inputs position force torque --eval-out /tmp/baselines_sd_bc_lstm_ft_n02.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.03 bopt_agent.gmm.model=models/bc/lstm_ft.npz --bc-inputs position force torque --eval-out /tmp/baselines_sd_bc_lstm_ft_n03.csv" \
                               "python scripts/main.py sliding_door_scenario --mode eval-lstm --deep-eval 100 --overrides env.noise.position.variance=0.05 bopt_agent.gmm.model=models/bc/lstm_ft.npz --bc-inputs position force torque --eval-out /tmp/baselines_sd_bc_lstm_ft_n05.csv"
python scripts/csv_fusion.py data/baselines_sliding_door_bc.csv /tmp/baselines_sd_bc_*.csv
