type: real_drawer

action_frequency: 30

open_position: 0.15 # Meters

reference_frame: obs_shelf_top_drawer
drawer_frame: obs_shelf_bottom_drawer

robot:
  state_prefix: /franka_state_controller
  controllers_prefix: /controllers
  reference_frame: panda_link0
  endeffector_frame: panda_EE
  fingers: 
    - panda_finger_joint1
    - panda_finger_joint2
  initial_pose:
    q: [-0.13961599458314633, 0.2669967083972797, 0.29144731764731846, -2.0875147196146826, 0.39374591070779785, 2.622371712433458, -0.1421404812684186]  # Starting point for IK and for frequent robot reset
    gripper_width: 0.05
    position:
      min: [0.4, -0.1, 0.3]
      max: [0.5,  0.1, 0.45]
  joint_reset_frequency: 5  # Return the robot to the original q pose every n steps
  stiffness:
    linear: 300
    angular: 20
