type: sliding_door

action_frequency: 30

goal_threshold: 0.395 # Degrees

door:
  path: package://bopt_gmm/objects/sliding_door.urdf
  reference_link: base_link
  sampler:
    min: [0.65, -0.2, 0, -0.2]
    max: [0.75, 0.2, 0,  0.2]

noise:
  position:
    variance: 0.0
    constant: true

robot:
  path: package://bopt_gmm/robots/panda_hand.urdf
  eef: panda_hand_tcp
  ft_joint: panda_hand_joint
  fingers: 
    - panda_finger_joint1
    - panda_finger_joint2
  initial_pose:
    q: [0, -0.2, 0.0, -2.5, 1.6, 2.6, 0.7853981633974483, 0]  # only used for IK
    orientation: [-2.2, 0, -1.57]
    position:
      min: [0.35, -0.1, 0.15]
      max: [0.55,  0.1, 0.45]
    gripper_width: 0.05
