type: sliding_door

action_frequency: 30

goal_threshold: 0.15 # Degrees

door:
  path: package://bopt_gmm/objects/hatch_door.urdf

frame:
  path: package://bopt_gmm/objects/hatch_frame.urdf
  reference_link: base_link
  sampler:
    min: [0.3, -0.2, 0.04, -0.2]
    max: [0.4,  0.2, 0.04,  0.2]

noise:
  position:
    variance: 0.0
    constant: true

robot:
  path: package://bopt_gmm/robots/panda_hand.urdf
  eef: panda_hand_tcp
  ft_joint: panda_hand_joint
  fingers: 
    - panda_finger_joint1
    - panda_finger_joint2
  initial_pose:
    q: [0, -0.2, 0.0, -2.5, 1.6, 2.6, 0.7853981633974483, 0]  # only used for IK
    orientation: [-3.145, 0, 1.57]
    position:
      min: [0.40, -0.05, 0.25]
      max: [0.50,  0.05, 0.35]
    gripper_width: 0.05
