defaults:
  - door_scenario
  - override bopt@bopt_agent: online_gmm

bopt_agent:
  debug_gmm_path: online_gmm_model         # Prefix for saving the newly generated gmm
  data_path: demos_door/demo_*.npz
