defaults:
  - door_dbopt_force_5
  - regularization@bopt_agent.regularizer: base

bopt_agent:
  early_tell: 1
  base_accuracy: 1.0
  regularizer:
    f: p_joint
    b: 1
    min_val: 0.91
  gmm:
    var_adjustment: 0
