defaults:
  - drawer_scenario
  - override bopt@bopt_agent: bopt_gmm_dbopt

bopt_agent:
  base_accuracy: 0.65
  mean_range:  0.0
  sigma_range: 0.4
  opt_dims:
    means: null
    cvars:
      type: rotation
      unary: null
      nary:  null
