defaults:
  - env: sliding_door
  - bopt@bopt_agent: bopt_gmm_base

bopt_agent:
  gmm: 
    model: "models/gmm/sd_5p.npy"
    type: position
    force_norm: 1
  gripper_command: 0.5

env:
  observation:
    with_noise: False
