learning_rate: 3e-4 
alpha_lr: 3e-4
batch_size: 256
gamma: 0.99 
tau: 0.005 
replay_buffer_size: 3e5
warm_start_steps: 256
optimize_alpha: True
init_alpha: 0.2
model: null

sacgmm_steps: 30
episode_steps: 600

observations: null

actor:
  arch: [256, 256]

critic:
  arch: [256, 256]
  num: 2

