gamma: 0.99
tau: 0.005
lr_actor: 3e-4
lr_critic: 3e-4
lr_alpha: 3e-4
init_alpha: 0.01
batch_size: 256
warm_start_steps: 256
fill_strategy: 'random'
optimize_alpha: true

sacgmm_steps: 30      # Number of control steps per SACGMM step
episode_steps: 600    # Maximum number of control steps

observations: null    # Environment observations to pass to SACGMM

# Actor architecture
actor:
  hidden_layers: 2
  hidden_dim: 256
  init_w: 0.001

# Critic architecture
critic:
  hidden_layers: 2
  hidden_dim: 256
  init_w: 0.001

replay_buffer:
  max_size: 10000
  load_path: null
  selection_strategy: incumbent_num  # | steps | episodes | incumbent_gmm_limit | incumbent_limit | incumbent_gmm_num
  incumbent_to_pick: 3               # Only for "incumbent_num" and "incumbent_gmm" strategy
  episode_count: 100                 # Only for "episodes" strategy and "incumbent_limit"
  step_count: 100000                 # Only for steps take

observation_processors:
  rgb_gripper: resnet18
