gamma: 0.99
tau: 0.005
lr_actor: 3e-4
lr_critic: 3e-4
lr_alpha: 3e-4
init_alpha: 0.01
batch_size: 256
warm_start_steps: 256
fill_strategy: 'random'
replay_buffer_size: 100000
replay_buffer_path: null
optimize_alpha: true

sacgmm_steps: 30      # Number of control steps per SACGMM step
episode_steps: 600    # Maximum number of control steps

observations: null    # Environment observations to pass to SACGMM

# Actor architecture
actor:
  hidden_layers: 2
  hidden_dim: 256
  init_w: 0.001

# Critic architecture
critic:
  hidden_layers: 2
  hidden_dim: 256
  init_w: 0.001

